jaffle_shop:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"

      # User/password auth
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"

      role: 'ACCOUNTADMIN'
      database: 'RAW'
      warehouse: 'COMPUTE_WH'
      schema: 'JAFFLE_SHOP'
      threads: 1
      client_session_keep_alive: False
      query_tag: 'dbt-demo_tag'

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: True # default: True if client_session_keep_alive is False, otherwise None